# store project 
POST http://localhost:3005/api/projects/
Content-Type: application/json

{
    "title" : "home-next",
    "color" : "pink",
    "order": 3,
    "priority": 5
}
### 

# store sprint 
POST http://localhost:3005/api/sprints/
Content-Type: application/json

{
    "title" : "⚠️ fixing bugs",
    "type" : "dev", 
    "project": "5fa6ab69b475bf28cf17d8bf",
    "start": "2020-11-02",
    "end": "2020-11-17"
}
###

# store task 
POST http://localhost:3005/api/tasks/
Content-Type: application/json

{
    "title" : "PUT api user",
    "sprint": "5fa5cf926912175d553e3ab6"
}
###

###
GET http://localhost:3005/api/projects/
###

###
GET http://localhost:3005/api/sprints/
###

